name: Run Scrapper Everyday

on:
  schedule:
    - cron '55 16 * * *'

jobs:
  build-container:
  runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker Build
      run: docker-compose build
    
    - name: Scrap Alcoholes
      run: docker-compose up

