name: Run Scrapper Everyday

on:
  schedule:
    # Run every dat at 20:15 - UTC
    - cron: '15 20 * * *'

jobs:
  containerized-main:
    runs-on: ubuntu-latest
    name: "Scrap Alcoholes"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Build
        run: docker-compose build
      
      - name: Scrap Alcoholes
        run: docker-compose up
